### ISSUE TITLE
2023/01/10 Frontend キャッチアップ

### ISSUE THREAD

**Issue by lemonadern** [youngeek-0410/dev#19]

**Comment by sora-ichigo** [comment]
Format

## どんな章だったか

## 何がキモか

## 知らなかった、面白かった話

**Comment by sora-ichigo** [comment]
前回やった時の議事録 https://github.com/youngeek-0410/dev/issues/15

**Comment by sora-ichigo** [comment]
## More on Functions
https://www.typescriptlang.org/docs/handbook/2/functions.html


 [TypeScript: Documentation - More on Functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#other-types-to-know-about) 以降時間なくて読めてない 😢

## どんな章だったか
Function Type により良い型をつけるためのtips集。基本的なシグネチャの話からgenerics, overload の話まで出てきてレベルが高かった。（それぞれにtipsが詰まっててよかった）
## 何がキモか
* どんなシグネチャがあるのか
* 基本的には TypeScript の型推論に頼ろう
  * 自分で書かなくて良い型は書かない
  * 呼び出し側への配慮につながる
* generics とは2つの型に関連性があるときにそれを説明するもの
  * In TypeScript, generics are used when we want to describe a correspondence between two values

## 知らなかった、面白かった話
* Function Type も construct 書けるの初めて知った
  * https://www.typescriptlang.org/docs/handbook/2/functions.html#construct-signatures
* generics(constraints) の型付けミスってる例
* [TypeScript: Documentation - More on Functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#working-with-constrained-values)
  * 確かに言われてみれば
  * 謎に苦手意識ある章 Constraints
  * https://www.typescriptlang.org/docs/handbook/2/functions.html#constraints
* Guidelines for Writing Good Generic Functions
  * [TypeScript: Documentation - More on Functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#push-type-parameters-down)
    * 出来るだけ Constrants ではなく型パラメタ自体を使って型付けする
      * Constraints を使うと TypeScript は Constraints のみで型の解決をしてしまう
    * これそもそも3つ目のtipsを踏んでてそっちのが気になってよくわからない
  * [TypeScript: Documentation - More on Functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#push-type-parameters-down) 
    * 推論できる型をわざわざ使い手側に書かせるな
  * [TypeScript: Documentation - More on Functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#type-parameters-should-appear-twice)
    * ２回以上登場しない type parameter は generics じゃなくても良い
* Writing Good Overloads
  * 可能であれば overload ではなく union を使おう
    * > This is much better! Callers can invoke this with either sort of value, and as an added bonus, we don’t have to figure out a correct implementation signature.
    * overload は単一のoverloadにしか型を解決できないし、呼び出しがわがいちいち最適なシグネチャを探し出す必要がある
* this parameter の話
  * [TypeScript: Documentation - More on Functions](https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function) 前回話したやつ

**Comment by lemonadern** [comment]
# Object Types
https://www.typescriptlang.org/docs/handbook/2/objects.html

## どんな章だったか
オブジェクトに型をつけるための知識が並んでいる。readonly 関連の説明が手厚い

- Property Modifiers の話
  - `readonly`
  - `?` (optional properties)
  - index signature
  - mapped types へのリンクが貼られ、optional, readonly を除外した型をつくったりもできるよ という言及とかも
- オブジェクトの拡張を考える
  - inderface の拡張 (`extends`)
  - 交差型 (Intersection Types)
  - interfaceの拡張 と type の交差型、どちらを使うかみたいな話も
- ジェネリクスを使ったオブジェクト
- 配列とタプル
  - readonly のときの挙動

## 何がキモか
- 構造的部分型でのオブジェクトに対する考え方を把握する
- readonly に何が期待できるのかを知る
  - It’s important to manage expectations of what readonly implies. It’s useful to signal intent during development time for TypeScript on how an object should be used.

## 知らなかった、面白かった話
TypeScript は Object Types 同士の互換性チェック時にはプロパティの readonly 属性を確認しない

readonly に何を期待できるのか（readonly が何を示しているのか）を正しく知っているのが大事
```ts
interface Person {
  name: string;
  age: number;
}
 
interface ReadonlyPerson {
  readonly name: string;
  readonly age: number;
}
 
let writablePerson: Person = {
  name: "Person McPersonface",
  age: 42,
};
 
// 代入できる
let readonlyPerson: ReadonlyPerson = writablePerson;
    // ^? let readonlyPerson: ReadonlyPerson
// 書き換えもできる
console.log(readonlyPerson.age); // prints '42'
writablePerson.age++;
console.log(readonlyPerson.age); // prints '43'
```


 Array を ReadonlyArray に代入するのは不可 （そりゃそう？）
```ts
let x: readonly string[] = [];
let y: string[] = [];
 
x = y;

y = x; 
//  ^  The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.
```

tuple で Optional な要素を宣言すると、そのタプルの length にも推論が効いてる（すごい）
```ts
type Either2dOr3d = [number, number, number?];
 
function setCoordinate(coord: Either2dOr3d) {
  const [x, y, z] = coord;
              // ^? const z: number | undefined
 
  console.log(`Provided coordinates had ${coord.length} dimensions`);
                                                // ^?  (property) length: 2 | 3
}
```

**Comment by re-taro** [comment]
# Type manipulation
https://www.typescriptlang.org/docs/handbook/2/types-from-types.html
## どんな章だったか
- 様々なType manipulationが網羅的に説明されている
  - 1章1ケース
## 何がキモか
- 様々な型演算子を組み合わせることで、複雑な演算や値を簡潔かつ保守的に表現することができる。
## 知らなかった、面白かった話
- `{ [k: string]: boolean };`という型の時`keyof`は`string | number`を返す
  - JavaScriptのオブジェクトキーは常に文字列に強制されるから
- オーバーロードされた関数型など`infer`で推論する型が複数ある場合、最後から推論される
- Conditional Typesにunionを渡すと一般的には分配される。
```ts
type ToArray<Type> = Type extends any ? Type[] : never;
 
type StrArrOrNumArr = ToArray<string | number>;
//    ^? type StrArrOrNumArr = string[] | number[]
```
  - これは望ましい動作だけど、もし分配したくない場合は`extends`の両辺の型を`[]`で囲んであげる必要がある
```ts
type ToArrayNonDist<Type> = [Type] extends [any] ? Type[] : never;

type StrArrOrNumArr = ToArrayNonDist<string | number>;
//    ^? type StrArrOrNumArr = (string | number)[]
```
- Mapping Typeに渡される型に`readonly`や`?`がついている場合、それらはMapping Typeで作られた型にも影響する。
  - 消すためには`+`や`-`をつける
```ts
type CreateMutable<Type> = {
  -readonly [Property in keyof Type]: Type[Property];
};
 
type LockedAccount = {
  readonly id: string;
  readonly name: string;
};
 
type UnlockedAccount = CreateMutable<LockedAccount>;
//    ^? type UnlockedAccount = { id: string; name: string; }
```
```ts
type Concrete<Type> = {
  [Property in keyof Type]-?: Type[Property];
};
 
type MaybeUser = {
  id: string;
  name?: string;
  age?: number;
};
 
type User = Concrete<MaybeUser>;
//    ^? type User = { id: string; name: string; age: number; }
```
- `as`を使うことでMappingされた型をもう一回Mappingすることができる
  - 例としては全部Capitalizeするとか
- `as`の右辺で`never`を返すとそのkeyをフィルタリングすることができる
  - `Execlude`とかと合わせると便利
- テンプレートリテラル型が一番使えるのは型の情報から新しい文字列を作る時
```ts
type PropEventSource<Type> = {
    on<Key extends string & keyof Type>
        (eventName: `${Key}Changed`, callback: (newValue: Type[Key]) => void ): void;
};

declare function makeWatchedObject<Type>(obj: Type): Type & PropEventSource<Type>;

const person = makeWatchedObject({
  firstName: "Saoirse",
  lastName: "Ronan",
  age: 26
});

person.on("firstNameChanged", newName => {
    //                        ^? type newName = string
    console.log(`new name is ${newName.toUpperCase()}`);
});

person.on("ageChanged", newAge => {
    //                  ^? type newAge = number
    if (newAge < 0) {
        console.warn("warning! negative age");
    }
})
```
