### ISSUE TITLE
2022/10/22: Frontendキャッチアップ

### ISSUE THREAD

**Issue by igsr5** [youngeek-0410/dev#2]
w/ @igsr5 @lemonadern

話したことを雑にメモっていく

**Comment by igsr5** [comment]
## 話したこと

- 2週ごと1時間でやる
  - スキップしない
  - 予定合わなかったら別日にずらす
  - 曜日固定ではなく、毎回次の時間を決める

**Comment by igsr5** [comment]
- キャッチアップしたいトピックは Project で管理していく(とりあえずお試し)
  - https://github.com/orgs/youngeek-0410/projects/4/views/1
  - 興味があるトピックは `Topic Backlog` に
  - 毎回、次やるトピックを `Next Topic` に入れる
  - 終わった Topic は `Done` に
  - 議事録 issue は `Issue` に

**Comment by igsr5** [comment]
- この議事録 issue について
  - 頑張らない
  - 雑にメモを投げていく

**Comment by sora-ichigo** [comment]
- `Frontend キャッチアップ` について
  - モチベ:
    - Frontend の最新技術に追いつけるになりたい
    - ブログとかTwitterとかで何となく情報は入ってくるけど、ちゃんと自分で動かせてることが少ない
  - やること:
    - 自分で実際にコードを書いて試してみる時間をとる
    - 「このサイトのこれどう作るんだろう？」みたいな疑問を解消する

**Comment by igsr5** [comment]
とりあえず @igsr5 @lemonadern の2人でやる
（あまり人集めても大変だし続かない気がするので）
