### ISSUE TITLE
2023/01/20 Frontend キャッチアップ

### ISSUE THREAD

**Issue by lemonadern** [youngeek-0410/dev#20]
前回：https://github.com/youngeek-0410/dev/issues/19

**Comment by sora-ichigo** [comment]
https://www.typescriptlang.org/cheatsheets を読む

**Comment by sora-ichigo** [comment]
https://www.typescriptlang.org/static/TypeScript%20Control%20Flow%20Analysis-8a549253ad8470850b77c4c5c351d457.png

assertion functions 初めて見た

**Comment by sora-ichigo** [comment]
![Image](https://user-images.githubusercontent.com/66525257/213696197-3260e388-1883-47c1-9f10-08cf76f440c8.png)



![Image](https://user-images.githubusercontent.com/66525257/213696204-9dca3933-7eea-4c69-a9c8-082e83b94ac4.png)

**Comment by sora-ichigo** [comment]
https://www.typescriptlang.org/static/TypeScript%20Interfaces-34f1ad12132fb463bd1dfe5b85c5b2e6.png


![Image](https://user-images.githubusercontent.com/66525257/213696883-5b98b0c8-5a13-483c-b357-e1467456deef.png)

**Comment by sora-ichigo** [comment]
![Image](https://user-images.githubusercontent.com/66525257/213697085-767ae6f8-ed2d-4fd0-a8bb-cc281971ea7e.png)

初めて知ったw

**Comment by sora-ichigo** [comment]
![Image](https://user-images.githubusercontent.com/66525257/213699243-4449a070-5822-4104-b020-41e07f39d352.png)



merge multiple js interface 
前方が優先される

**Comment by sora-ichigo** [comment]
type alias version の merge

![Image](https://user-images.githubusercontent.com/66525257/213699190-0833016b-27f9-4506-8001-45eccd39e616.png)

**Comment by sora-ichigo** [comment]
![Image](https://user-images.githubusercontent.com/66525257/213699355-0a229969-0bf8-466a-8506-7101f344e52f.png)

今回だとそんな型は存在しない

**Comment by sora-ichigo** [comment]
存在しない = never なので↓ならいける


![Image](https://user-images.githubusercontent.com/66525257/213699462-c082032f-2a99-4811-bdea-acd9849b5605.png)

**Comment by sora-ichigo** [comment]
![Image](https://user-images.githubusercontent.com/66525257/213701552-534dd506-4589-4861-9b94-5f2883cc792e.png)

private, public, protected の機能は ts only
